#!/usr/bin/env bash

# This script generates all local-only host and user configuration files
# from scratch. It does NOT depend on a template file.
# It MUST be run with sudo, e.g.: sudo bash Host-Config.sh

set -e

# --- Configuration ---
# Ensure the script is run from the correct directory (/etc/nixos)
cd /etc/nixos

HOST_FILE="Host/Host.nix"
USER_DIR_BASE="Users"

# --- 1. Get User Input ---
echo "--- NixOS Host Setup ---"
read -p "Enter the desired HOSTNAME for this machine: " HOST_NAME
read -p "Enter the primary USERNAME for this machine: " USERNAME

# --- 2. Define Paths ---
USER_DIR="$USER_DIR_BASE/$USERNAME"
USER_FILE="$USER_DIR/Applications.nix"
SYMLINK_PATH="/home/$USERNAME/Applications.nix"

echo "Host File will be created at: $HOST_FILE"
echo "User File will be created at: $USER_FILE"

# --- 2b. Move Hardware Configuration (Request 2) ---
HARDWARE_FILE="hardware-configuration.nix"
NEW_HARDWARE_PATH="Host/$HARDWARE_FILE"
if [ -f "$HARDWARE_FILE" ]; then
    echo "Moving $HARDWARE_FILE to $NEW_HARDWARE_PATH..."
    sudo mv "$HARDWARE_FILE" "$NEW_HARDWARE_PATH"
else
    echo "Warning: $HARDWARE_FILE not found. Skipping move."
    echo "If this is a new install, you may need to run nixos-generate-config first."
fi

# --- 3. Create Host Configuration File ---
echo "Creating host configuration at $HOST_FILE..."
sudo mkdir -p "$(dirname "$HOST_FILE")"

# Use tee to write the entire file as root.
# Note: We escape $ with \${} for Nix variables, but not for $USERNAME
# and $HOST_NAME, which we want Bash to expand.
sudo tee "$HOST_FILE" > /dev/null <<EOF

# This file was generated by Host-Config.sh
# It contains local-only settings for this specific machine.

{ config, pkgs, lib, ... }:

let
  primaryUser = "anonymous";
  privatePackagePath = ../Users/${primaryUser}/Applications.nix;

  isNvidia = builtins.pathExists "/proc/driver/nvidia/version";
  isAmd = !isNvidia;

  isKDE = true;
  isGnome = !isKDE;

in
{
  networking.hostName = "anonymous";

  users.users.${primaryUser} = {
    isNormalUser = true;
    description = "${primaryUser}'s Account";
    extraGroups = [ "wheel" "networkmanager" "docker"];
  };

  imports =
   [
      ./hardware-configuration.nix
      ./Unstable.Nix
      ../Users/${primaryUser}/Applications.nix
    ]
    # These conditional imports are appended
    ++ (lib.optional isKDE ./Desktop-Enviroment/KDE.nix)
    ++ (lib.optional isGnome ./Desktop-Enviroment/Gnome.nix)
    ++ (lib.optional isAmd ./Graphics/AMD.nix)
    ++ (lib.optional isNvidia ./Graphics/Nvidia.nix);

}
EOF

# --- 4. Create User's Private Application File (Request 1 & 4) ---
echo "Creating user application directory at $USER_DIR..."
sudo mkdir -p "$USER_DIR"

echo "Creating minimal application file at $USER_FILE..."
sudo tee "$USER_FILE" > /dev/null <<EOF
{ config, pkgs, ... }:

{
  # --- Module Toggles ---
  # Gaming.enable = true;
  # Proton-Suite.enable = true;

  # --- Private Packages ---
  # (Packages are added here by the Nix Software Center)
}
EOF

# --- 5. Set Permissions and Create Symlink ---
echo "Setting permissions for $USER_DIR..."
sudo mkdir -p "/home/$USERNAME"
sudo chown -R "$USERNAME:users" "$USER_DIR"
sudo chown "$USERNAME:users" "/home/$USERNAME"

echo "Creating symlink at $SYMLINK_PATH..."
# Create symlink (sf = symbolic, force)
sudo ln -sf "/etc/nixos/$USER_FILE" "$SYMLINK_PATH"
sudo chown -h "$USERNAME:users" "$SYMLINK_PATH"

echo "---"
echo "local configuration is complete."
